# Generated by Django 4.0.6 on 2022-11-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_category1_category_ctg1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category1',
            new_name='Categoryy',
        ),
    ]
