# Generated by Django 4.0.6 on 2022-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_rename_category1_categoryy'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryy',
            name='name',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
    ]
