# Generated by Django 4.0.6 on 2022-11-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_categoryy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ctg1',
            new_name='ctg',
        ),
    ]
